[package]
name = "rs_music_server"
version = "0.1.0"
authors = ["STSchiff <chrisheib@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
walkdir = "2"
actix-files = "0.4"
rand = "0"

[dependencies.rusqlite]
version = "0.24"
features = ["bundled"]