[package]
name = "rs_music_server"
version = "0.1.0"
authors = ["STSchiff <chrisheib@gmx.de>"]
edition = "2018"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3"
actix-files = "0.5"
json = "0.12"
walkdir = "2.3"
rand = "0.8"
rusqlite = {version = "0.24", features = ["bundled"]}
audiotags = "0.2" # tags
mp3-duration = "0.1" # song length
stable-eyre = "0.2"